#!/usr/bin/env bash
set -e

opt_package_conf="pacman.conf"
opt_package_lst="packages.x86_64"

work_dir="work_dir"
tmp_dir="${work_dir}/tmp"
root_dir="${work_dir}/rootfs"
esp_dir="${work_dir}/esp"
iso_dir="${work_dir}/iso"

prepare_rootfs() {
    mkdir -p "${root_dir}"
    cp -af --no-preserve=ownership,mode -T airootfs "${root_dir}"
    local -a package_lst
    mapfile -t package_lst < <(sed '/^[[:blank:]]*#.*/d;s/#.*//;/^[[:blank:]]*$/d' "${opt_package_lst}")

    pacstrap -C "${opt_package_conf}" -c -G -M -- "${root_dir}" "${package_lst[@]}"
}

prepare_esp() {
    mkdir -p "${esp_dir}/EFI/BOOT"
    local grubmodules=(all_video at_keyboard boot btrfs cat chain configfile echo efifwsetup efinet exfat ext2 f2fs fat font \
                 gfxmenu gfxterm gzio halt hfsplus iso9660 jpeg keylayouts linux loadenv loopback lsefi lsefimmap \
                 minicmd normal ntfs ntfscomp part_apple part_gpt part_msdos png read reboot regexp search \
                 search_fs_file search_fs_uuid search_label serial sleep tpm udf usb usbserial_common usbserial_ftdi \
                 usbserial_pl2303 usbserial_usbdebug video xfs zstd)
    grub-mkstandalone -O x86_64-efi \
        --modules="${grubmodules[*]}" \
        -o "${esp_dir}/EFI/BOOT/BOOTx64.EFI" \
        grub/grub.cfg
}

make_iso() {
    mkdir -p "${tmp_dir}"

    local efiboot_imgsize="$(du -bcs -- "${esp_dir}/EFI/BOOT/BOOTx64.EFI" 2>/dev/null | awk 'END { print $1 }')"
    local imgsize_kib="$(
        awk '
        function ceil(x){return int(x)+(x>int(x))}
        function byte_to_kib(x){return x/1024}
        function mib_to_kib(x){return x*1024}
        END {print mib_to_kib(ceil((byte_to_kib($1)+8192)/1024))}' <<<"${imgsize_bytes}"
        )"
    local efibootimg="${tmp_dir}/efibootimg.img"
    rm -rf "${efibootimg}"
    mkfs.fat -C -F 32 "${efibootimg}" "${imgsize_kib}"
    mmd -i "${efibootimg}" ::/EFI ::/EFI/BOOT
    mcopy -i "${efibootimg}" "${esp_dir}/EFI/BOOT/BOOTx64.EFI" ::/EFI/BOOT/BOOTx64.EFI
}

main() {
    prepare_rootfs
    prepare_esp
    make_iso
}

main "$@"

