name: ci

on:
  push:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Build ISO
        run: |
          echo 123
      - uses: actions/upload-artifact@v4
        with:
          name: archiso
          path: out_dir/

