name: ci

on:
  push:
    branches:
      - master
      - mini-server

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Build ISO
        run: |
          pacman-key --init
          pacman-key --populate
          pacman -Syu --noconfirm
          pacman -S --noconfirm grub libisoburn dosfstools mtools arch-install-scripts erofs-utils
          ./tools/build -o archlinux.iso
      - uses: actions/upload-artifact@v4
        with:
          name: archiso
          path: archlinux.iso

